name: E2E Regression

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to run?
        required: true
        options:
          - electron
          - chrome
          - firefox
      environment:
        type: choice
        description: Which environment to run?
        required: true
        options:
          - qa
          - staging
          - prod
  schedule:
    - cron: '0 8 * * *'

jobs:
  cypress:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run headlessMode -- --env env=${{ github.event.inputs.environment || 'prod' }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/**
            cypress/videos/**
          retention-days: 30
